###############
## 
####

# GPU: [0,1,2,3]
GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 2
  NUM_EPOCHS: 200
  # NEPOCH_DECAY: [10]
  # LR_INITIAL: 2e-4
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: TRUE
  TRAIN_PS: 512
  VAL_PS: 512
  TRAIN_DIR: 'D:/code/MPRNet/deblur_HE_IHC_paired_remove_background_+-3um_small/train' # path to training data
  VAL_DIR: 'D:/code/MPRNet/deblur_HE_IHC_paired_remove_background_+-3um_small/test'    # path to validation data
  SAVE_DIR: 'checkpoint_HE_IHC'     # path to save models and images
  SAVE_IMAGES: TRUE
